name: vets_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.2
  # Curved Navigation Bar
  curved_navigation_bar: ^1.0.3
  # Provider
  provider: ^6.0.3
  # Screen Util
  flutter_screenutil: ^5.5.4
  # Font Awesome
  font_awesome_flutter: ^10.1.0
  # Google Fonts
  google_fonts: ^3.0.1
  # SVG
  flutter_svg: ^1.1.5
  # Loading
  flutter_spinkit: ^5.1.0
  loading_animation_widget: ^1.2.0+3
  # Validators
  validators: ^3.0.0
  # Firebase
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.9
  cloud_firestore: ^3.4.9
  google_sign_in: ^5.4.2
  # Toast
  fluttertoast: ^8.0.9
  # Date picker
  date_picker_timeline: ^1.2.3
  # Image picker
  image_picker: ^0.8.5+3
  animated_text_kit: ^4.2.2
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.2.50
  weekday_selector: ^1.1.0
  # Rating
  flutter_rating_bar: ^4.0.1
  # Cache Network Image
  cached_network_image: ^3.2.2
  # language
  easy_localization: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/details/
    - assets/icons/
    - assets/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
